### ISSUE TITLE
so linger

### ISSUE THREAD

**Issue by choeflake** [lump/pjl#2]
Hi, 

Why is the socket linger set to false and keep-alive also to false in SocketClient?

(https://github.com/lump/pjl/blob/master/src/net/lump/print/jetdirect/SocketClient.java lines 68,69)

Kind regards,
Cornelis

**Comment by lump** [comment]
If I remember correctly (it's been a few years), I have setSoLinger because
I want the connection to really close when I tell it to close.  I also was
running this on an application server.  The other part is the way JetDirect
printing works: it only lets one connection do work at a time, because a
printer is a physical resource.  If the Socket was mysteriously kept up in
the jvm, it would not allow other JetDirect clients to use the printer.   A
print job needs to connect, do its work, and disconnect, not just pretend
to disconnect.

**Comment by choeflake** [comment]
Thanks, that makes it clear for me!
